#!/usr/bin/env node
// Generates site/llms-full.txt by inlining the documentation that site/llms.txt
// only links to.
//
//   node scripts/build-llms.js
//   node scripts/build-llms.js --check    exit 1 if the file is out of date
//
// The point of llms-full.txt is that a model can read the whole project in one
// fetch instead of following five links. Generating it means it cannot drift
// away from the docs it claims to reproduce, which is the usual fate of a
// hand-maintained copy.

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const OUT = path.join(ROOT, "site", "llms-full.txt");
const ORIGIN = "https://noluyorabi.github.io/cockpit-claude";

// Order matters: it is the order a reader should meet the project in.
const SOURCES = [
  { file: "README.md", title: "README" },
  { file: "docs/CONFIG.md", title: "Configuration reference" },
  { file: "docs/FAQ.md", title: "FAQ" },
  { file: "docs/ROADMAP.md", title: "Roadmap" },
  { file: "CONTRIBUTING.md", title: "Contributing" },
  { file: "SECURITY.md", title: "Security policy and threat model" },
  { file: "CHANGELOG.md", title: "Changelog" },
];

// Badge rows, centred HTML blocks and image embeds carry nothing for a reader
// that cannot see them, and they cost tokens. The prose is the payload.
function stripMarkup(md) {
  return md
    .replace(/<p align="center">[\s\S]*?<\/p>/g, "")
    .replace(/^!\[[^\]]*\]\([^)]*\)\s*$/gm, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

function build() {
  const parts = [
    "# cockpit-claude, full documentation",
    "",
    "> Every document in the repository, inlined. This is the long form of "
      + `${ORIGIN}/llms.txt, which links to these instead of reproducing them.`,
    "",
    `Source of truth: https://github.com/noluyorAbi/cockpit-claude`,
    `Package: https://www.npmjs.com/package/cockpit-claude`,
    `Site: ${ORIGIN}/`,
    "",
    "Generated by scripts/build-llms.js. Do not edit by hand; edit the "
      + "documents it reads and regenerate.",
    "",
  ];

  for (const { file, title } of SOURCES) {
    const abs = path.join(ROOT, file);
    if (!fs.existsSync(abs)) {
      console.error(`missing source: ${file}`);
      process.exitCode = 1;
      continue;
    }
    parts.push("", "=".repeat(76), `# ${title} (${file})`, "=".repeat(76), "");
    parts.push(stripMarkup(fs.readFileSync(abs, "utf8")));
  }

  parts.push("");
  return parts.join("\n");
}

const next = build();
const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : null;

if (process.argv.includes("--check")) {
  if (current !== next) {
    console.error("site/llms-full.txt is out of date. Run: node scripts/build-llms.js");
    process.exit(1);
  }
  console.log("site/llms-full.txt is up to date");
} else {
  fs.writeFileSync(OUT, next);
  const kb = (Buffer.byteLength(next) / 1024).toFixed(1);
  console.log(`wrote site/llms-full.txt (${kb} kB, ${SOURCES.length} documents)`);
}
